### ISSUE TITLE
Some questions about running the code 

### ISSUE THREAD

**Issue by sunjing1102628** [uoe-agents/PO-GPL#1]
Dear Authors,

Excuse the liberty I may take to write you this issue.
 My name is Sun Jing. My research is focusing on the Ad hoc framework and I have recently read your paper “
A General Learning Framework for Open Ad Hoc Teamwork Using Graph-based Policy Learning”. 

When I run the code, I utilized the command "pip install ."  to install the environment of lbforaging. However when I run the command "./run_gpl.sh", I got the error of "**FileNotFoundError: [Errno 2] No such file or directory: '/Users/sunjing/miniconda3/envs/myenv/lib/python3.7/site-packages/lbforaging/agents/A2CAssets/agent_policy_0_40**". The detail are as follows.  If convenient, would it be possible to give me an explanation to me at your convenience?

Traceback (most recent call last):
  File "gpl_only_train.py", line 1087, in <module>
    model_trainer.run()
  File "gpl_only_train.py", line 726, in run
    test_obses = self.preprocess(env.reset().item(0))
  File "/Users/sunjing/miniconda3/envs/myenv/lib/python3.7/site-packages/gym/vector/sync_vector_env.py", line 79, in reset
    observation = env.reset()
  File "/Users/sunjing/miniconda3/envs/myenv/lib/python3.7/site-packages/lbforaging/foraging/environment_adhoc.py", line 878, in reset
    agent_type, agent_controller = self.agent_type_selector()
  File "/Users/sunjing/miniconda3/envs/myenv/lib/python3.7/site-packages/lbforaging/foraging/environment_adhoc.py", line 791, in agent_type_selector
    return agent_type, A2CAgent(a2c_index)
  File "/Users/sunjing/miniconda3/envs/myenv/lib/python3.7/site-packages/lbforaging/agents/A2CAgents.py", line 17, in __init__
    self.load_parameters(current_path+"/A2CAssets/agent_policy_"+str(policy_type)+"_40")
  File "/Users/sunjing/miniconda3/envs/myenv/lib/python3.7/site-packages/lbforaging/agents/A2CAgents.py", line 29, in load_parameters
    self.policy.load_state_dict(torch.load(param_dir))
  File "/Users/sunjing/miniconda3/envs/myenv/lib/python3.7/site-packages/torch/serialization.py", line 581, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/sunjing/miniconda3/envs/myenv/lib/python3.7/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/sunjing/miniconda3/envs/myenv/lib/python3.7/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sunjing/miniconda3/envs/myenv/lib/python3.7/site-packages/lbforaging/agents/A2CAssets/agent_policy_0_40'

**Comment by IgnacioCarlucho** [comment]
Hi sunjing, 

Sorry for the late reply. 

For installing LBF could you try the following. First cd into the LBF folder:

`cd PO-GPL/envs/LBF/`

And then install the environment with the following command: 

`pip install -e .`

After that try runing "./run_gpl.sh" again. The issue should be fixed. 

Let me know if you have any more problems!

Ignacio
